# Generated by Django 5.2.17 on 2026-08-10 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='ID from the music SDK/API, once integrated. Optional for now.', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public — anyone can find and join'), ('private', 'Private — invite only')], default='public', max_length=10)),
                ('vote_permission', models.CharField(choices=[('everyone', 'Everyone can vote'), ('invited_only', 'Only invited guests can vote'), ('location_time_restricted', 'Only people at the venue, during the time window, can vote')], default='everyone', max_length=30)),
                ('venue_center_latitude', models.FloatField(blank=True, null=True)),
                ('venue_center_longitude', models.FloatField(blank=True, null=True)),
                ('allowed_distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('voting_opens_at', models.DateTimeField(blank=True, null=True)),
                ('voting_closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(help_text='The user who created this event.', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Waiting in the queue'), ('playing', 'Currently playing'), ('played', 'Already played')], default='queued', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs_added', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='events.event')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_to_events', to='events.song')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('event', 'song')},
            },
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('event', 'guest')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.eventsong')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event_song', 'voter')},
            },
        ),
    ]
