# Generated by Django 5.0.2 on 2026-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
