# Generated by Django 5.0.2 on 2026-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_song_album_art_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_art_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
