# Generated by Django 5.2.17 on 2026-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_song_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
