# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_preset',
            field=models.CharField(
                choices=[
                    ('party', 'Party'),
                    ('night_vibe', 'Night vibe'),
                    ('dj', 'DJ'),
                    ('summer_vibe', 'Summer vibe'),
                    ('rain', 'Rain'),
                    ('coding_vibe', 'Coding vibe'),
                    ('after_dark', 'After dark'),
                    ('vibes', 'Vibes'),
                ],
                default='party',
                max_length=20,
            ),
        ),
    ]
