# Generated by Django 5.2.17 on 2026-08-30 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_cover_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_song',
            field=models.ForeignKey(blank=True, help_text="The queue entry currently 'on air', authoritative on the backend regardless of who's connected. Set only by `sync_current_song`.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.eventsong'),
        ),
        migrations.AddField(
            model_name='event',
            name='current_song_started_at',
            field=models.DateTimeField(blank=True, help_text='When `current_song` started playing from position 0. Playback position is always derived as now() - this timestamp, never stored directly.', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='playback_type',
            field=models.CharField(choices=[('preview', '~30-second preview clip (Deezer)'), ('full', 'Full-length stream (Audius)')], default='preview', help_text='Whether `preview_url` plays a short clip or the full track — see `effective_duration_seconds`.', max_length=10),
        ),
    ]
