# Generated by Django 5.2.17 on 2026-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventguest',
            name='rsvp_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
