# Generated by Django 5.2.17 on 2026-08-31 06:02
# Split from the auto-generated migration: this is schema-only (add the
# two new toggle fields). The old `location_time_restricted` choice is
# deliberately left on vote_permission for one more migration, so the
# data migration that follows (0012) can still write that value while
# reading pre-migration rows — see 0012 and 0013.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventguest_rsvp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_restriction_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='time_restriction_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
