# Generated by Django 5.2.17 on 2026-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_location_time_restricted_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('live', 'Live — open as normal'), ('closed', 'Closed — still viewable/votable, but no new track suggestions'), ('canceled', 'Canceled — inaccessible to everyone but the host, even previous guests/members')], default='live', max_length=10),
        ),
    ]
