# Generated by Django 5.2.17 on 2026-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('live', 'Live — open as normal'), ('closed', 'Closed — still viewable/votable, but no new track suggestions'), ('canceled', 'Canceled — inaccessible to everyone but the host, even previous guests/members'), ('ghost_town', 'Ghost Town 👻 — no new track suggested in a while'), ('rip_attendance', 'RIP Attendance — no new track suggested in even longer'), ('party_of_nobody', 'Party of Nobody — no new track suggested in a long while')], default='live', max_length=20),
        ),
    ]
