# Generated by Django 5.2.17 on 2026-08-31 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, help_text='Cap on combined invited guests + self-joined members, between 2 and 100. Defaults to 100 if not set.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('live', 'Live — open as normal'), ('closed', 'Closed — still viewable/votable, but no new track suggestions'), ('canceled', 'Canceled — inaccessible to everyone but the host, even previous guests/members'), ('deleted', 'Deleted — soft-deleted by the host; only past guests/members can still view it'), ('ghost_town', 'Ghost Town 👻 — no new track suggested in a while'), ('rip_attendance', 'RIP Attendance — no new track suggested in even longer'), ('party_of_nobody', 'Party of Nobody — no new track suggested in a long while')], default='live', max_length=20),
        ),
    ]
