# Generated by Django 5.2.17 on 2026-09-10 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def merge_duplicate_daily_participations(apps, schema_editor):
    """Existing EventParticipation had one row per (event, user) — after
    the backfill above, every one of those rows for the same user now
    shares the same `date` ("today"), which would collide with the new
    (user, date) unique constraint below. Collapse them into one row per
    user, summing suggestion_count, before that constraint is created."""
    DailyParticipation = apps.get_model('events', 'DailyParticipation')
    seen_by_key = {}
    for row in DailyParticipation.objects.order_by('id'):
        key = (row.user_id, row.date)
        keeper_id = seen_by_key.get(key)
        if keeper_id is None:
            seen_by_key[key] = row.id
            continue
        keeper = DailyParticipation.objects.get(pk=keeper_id)
        keeper.suggestion_count += row.suggestion_count
        keeper.save(update_fields=['suggestion_count'])
        row.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventparticipation'),
    ]

    operations = [
        # FREE-tier suggestion/vote limits move from per-event to
        # per-(user, calendar day), across every event — see
        # events/services.py and events/models.py's DailyParticipation
        # doc comment.
        migrations.RenameModel(old_name='EventParticipation', new_name='DailyParticipation'),
        migrations.AlterUniqueTogether(
            name='dailyparticipation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailyparticipation',
            name='event',
        ),
        migrations.AddField(
            model_name='dailyparticipation',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyparticipation',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='daily_participations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(merge_duplicate_daily_participations, migrations.RunPython.noop),
    ]
