# Generated by Django 5.2.17 on 2026-09-10 00:00
"""
Split from 0019 into its own migration (own transaction) deliberately:
running this ALTER TABLE in the same transaction as 0019's RunPython
data migration — which UPDATEs/DELETEs rows on this same table — hits
Postgres's "cannot ALTER TABLE ... because it has pending trigger
events" restriction. Committing 0019 first clears that.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_dailyparticipation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyparticipation',
            unique_together={('user', 'date')},
        ),
    ]
