# Generated by Django 5.0.2 on 2026-08-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_remove_playlistsong_unique_position_per_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
