# Generated by Django 5.2.17 on 2026-08-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_playlistaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/covers/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover_preset',
            field=models.CharField(blank=True, choices=[('sunset', 'Sunset'), ('neon', 'Neon'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('midnight', 'Midnight')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='edit_permission',
            field=models.CharField(choices=[('everyone', 'Everyone (with access) can edit'), ('invited_only', 'Only invited collaborators can edit'), ('owner_only', 'Only the owner can edit')], default='everyone', max_length=20),
        ),
    ]
