# Generated by Django 5.2.17 on 2026-08-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
