# Generated by Django 5.2.17 on 2026-08-09 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('favorite_artist', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('favorite_genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hip_hop', 'Hip-Hop'), ('rap', 'Rap'), ('rnb', 'R&B'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('house', 'House'), ('techno', 'Techno'), ('metal', 'Metal'), ('punk', 'Punk'), ('reggae', 'Reggae'), ('country', 'Country'), ('folk', 'Folk'), ('soul', 'Soul'), ('funk', 'Funk'), ('indie', 'Indie'), ('alternative', 'Alternative'), ('latin', 'Latin'), ('afrobeat', 'Afrobeat'), ('kpop', 'K-Pop'), ('soundtrack', 'Soundtrack')], max_length=30), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
