# Generated by Django 6.0.4 on 2026-08-26 08:35

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field_visibility',
            field=models.JSONField(default=profiles.models._default_field_visibility),
        ),
    ]
