# Generated by Django 5.2.17 on 2026-08-30 22:02

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_external_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_preset_id',
            field=models.CharField(blank=True, choices=[('1', 'Avatar 1'), ('2', 'Avatar 2'), ('3', 'Avatar 3'), ('4', 'Avatar 4'), ('5', 'Avatar 5'), ('6', 'Avatar 6'), ('7', 'Avatar 7'), ('8', 'Avatar 8'), ('9', 'Avatar 9'), ('10', 'Avatar 10'), ('11', 'Avatar 11')], default=profiles.models._random_avatar_preset_id, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_type',
            field=models.CharField(choices=[('preset', 'Preset avatar'), ('external_url', 'External URL (from social sign-in)'), ('custom', 'Custom uploaded image')], default='preset', max_length=15),
        ),
    ]
