# Generated by Django 5.2.17 on 2026-09-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_randomize_existing_avatar_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
